### ISSUE TITLE
Refreshing the screen before windows to display windows

### ISSUE THREAD

**Issue by McParen** [foggynight/tomb#2]
Hello foggynight,

I played around with your game and stumbled upon the refresh issue:

```
(defun draw-initial-ui (scr player world note-win stat-win depth-win)
  "Draw the initial UI, not including the game view."
  ;; The screen must be refreshed before drawing in the child windows; unsure if
  ;; this is a bug in the croatoan library, or just how ncurses works.
  (crt:refresh scr)
```

In short: this is how ncurses works.

In detail: Your event loop at the end of main receives its events from the screen. Every time ncurses calls wgetch on a window, it implicitely *refreshes* that window. Every time you refresh overlapping windows, the last window you refresh is displayed on top of the other windows, but only if the window has been changed (or has just been created, or "touch"ed, both count as a change).

So what does your code do now? You create the screen, then you create the windows, both in main. Then you draw-initial-ui. Then you go back to main and run the event loop on screen.

If you refresh the screen in draw-initial-ui before the windows, the refresh marks it as unchanged, and when you then receive events from it later, it does not cover your windows because there are no new changes being made to it, you just read events from it and the refresh essentially has no visible effect.

If you do *not* refresh the screen in draw-initial-ui before refreshing the windows, it is still considered as *changed*, so when you receive the first event, an empty screen is displayed above your windows.

Refreshing scr before the windows "works" for you, but it is not a clean solution. The clean solution would be to either receive your input from one of the game windows and completely ignore the screen, or to touch and refresh the screen and the windows on every cycle of the main loop, i.e. to treat them like a stack. For refrence, see the croatoan examples [t09b](https://github.com/McParen/croatoan/blob/2f37560e95928c41f599b4d7795aeb2723e95cdd/test/clos.lisp#L1199) and [t09c](https://github.com/McParen/croatoan/blob/2f37560e95928c41f599b4d7795aeb2723e95cdd/test/clos.lisp#L1228).

If you encounter other issues and questions wrt ncurses or croatoan, please start an issue over at the repository, so that it can serve as a refrence for others or encourage others to chime in.

Greetings,
McParen

**Comment by foggynight** [comment]
Hello McParen,

Thank you very much for explaining the problem in such detail and for providing a couple of solutions; I wound up going with refreshing a stack containing the screen and windows. It was very straightforward to implement (especially given the examples), over and over I'm impressed with the croatoan interface, well done!

I apologize for not opening up an issue, I didn't want to pester you over my lack of ncurses experience, I figured I'd handle it when I got around to reading the ncurses docs about this but you beat me to it. I'll be sure to open an issue in the future, your explanations are excellent.

Thanks again,
foggynight
